name = input("masukan nama : ")
umur = input("masukan umur : ")
alamat = input("masukan alamat : ")
print = input("masukan jurusan : ")

print("\n---Biodata---")
print("Nama : " + nama)
print("Umur : " + umur)
print("Alamat : " + alamat)
print("Jurusan : " + jurusan)
